### ISSUE TITLE
Write test runner script

### ISSUE THREAD

**Issue by danielparton** [choderalab/ensembler#11]
Command-line syntax could be something like this:

```
ensembler test
ensembler integration_tests
```

Should be possible to run tests from any location, so the tests will need to be able to access test data stored in the install directory.

**Comment by danielparton** [comment]
I've refactored the testing framework so that tests can be run from any directory with `nosetests ensembler`. Closing this issue as it's no longer necessary to write a custom test runner script.

**Comment by jchodera** [comment]
Awesome!
