### ISSUE TITLE
Add travis continuous integration?

### ISSUE THREAD

**Issue by jchodera** [choderalab/ensembler#17]
I wonder if it would be useful to add travis continuous integration tests.  These could test the construction of a very small number of templates and targets for small proteins, though we would need to figure out how to install the non-conda-installable dependencies.

Something to think about if it becomes easy to satisfy those dependencies.

**Comment by danielparton** [comment]
Travis integration is now working and the build is passing. I also managed to have Travis CI install Modeller, so those tests are also run.

**Comment by jchodera** [comment]
Let's be sure the environment variables are encrypted

**Comment by danielparton** [comment]
Relevant environment variables are now encrypted.
