### ISSUE TITLE
Allow optional user-specified substitution matrix names

### ISSUE THREAD

**Issue by jchodera** [choderalab/ensembler#45]
It would be useful to generalize the [template-target alignment code](https://github.com/choderalab/ensembler/blob/master/ensembler/modeling.py#L400-L410) to allow the user to specify alternative substitution matrices available within [`Bio.SubsMat.MatrixInfo`](http://biopython.org/DIST/docs/api/Bio.SubsMat.MatrixInfo-module.html).

**Comment by danielparton** [comment]
Addressed in merged PR https://github.com/choderalab/ensembler/pull/54
