### ISSUE TITLE
Default Collision Frequency

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/ensembler#5]
So it looks like the default Langevin collision rate is set to 5.0 per picosecond (https://github.com/choderalab/msmseeder/blob/master/MSMSeeder/packaging.py#L114).  According to Michael's paper (http://pubs.acs.org/doi/abs/10.1021/ct400109a), I think this might be slightly too strong.  I think a better value might be around 0.5 per picosecond.

**Comment by jchodera** [comment]
It looks like the default collision rate for implicit solvent refinement is 20/ps.  Is this OK for the paper?

We can certainly mention in the paper that lower collision rates may help, and cite the work above.

**Comment by kyleabeauchamp** [comment]
I'm happy.  I brought this primarily for the eventual explicit solvent FAH simulations, which inherited values from here.
