### ISSUE TITLE
'module' object has no attribute 'Ward'

### ISSUE THREAD

**Issue by rafwiewiora** [choderalab/ensembler#59]
Just want to mention that currently conda installation is not functional due to the `cluster.Ward` deprecation in scikit-learn 0.17 and hence the exception thrown by msmbuilder. 

See here: https://github.com/msmbuilder/msmbuilder/issues/692

Installation of msmbuilder from Github repo rescues it.

**Comment by jchodera** [comment]
Can you try again?  Remove your github installation of `msmbuilder` (will have to do this manually) and try
```
conda uninstall ensembler msmbuilder mdtraj scikit-learn --yes
conda clean -plts --yes
conda install ensembler --yes
```
They have fixed the conda package for `msmbuilder` so that it should work now without changes.

**Comment by rafwiewiora** [comment]
Not quite, the msmbuilder is not fixed in the conda build yet, all that seems to have been done is forcing scikit-learn 0.16 rather than 0.17 as they mention in msmbuilder/msmbuilder#692. 

But:
```
conda install ensembler --yes
```

installs scikit-learn 0.17 as dependency. 

Still have to do:
```
conda remove scikit-learn --yes
conda install scikit-learn=0.16
```

**Comment by jchodera** [comment]
> Not quite, the msmbuilder is not fixed in the conda build yet, all that seems to have been done is forcing scikit-learn 0.16 rather than 0.17 as they mention in msmbuilder/msmbuilder#692.

Any idea why this is?  `ensembler` doesn't specify `scikit-learn` as a dependency, and `msmbuilder` specifies `scikit-learn <=0.16`, so unless you have an old cached package somewhere, it should be either pulling in 0.16 or earlier or say that it couldn't resolve a conflict in dependencies (if some other package is demanding 0.16).

Ah!  I forgot the `-i` argument to `conda clean`:
```
conda uninstall ensembler msmbuilder mdtraj scikit-learn --yes
conda clean -pltis --yes
conda install ensembler --yes
```

**Comment by rafwiewiora** [comment]
> and msmbuilder specifies scikit-learn <=0.16

This is the problem. `conda install msmbuilder` install the 3.3.0-np110py27_1 build, but they have corrected the scikit-learn dependency in the 3.3.0-np110py27_2 build. 

This is why I've asked this on Slack:

rafwiewiora [3:48 PM] 
What’s the conda command for installing a particular build?

conda install software-x=version works ok, but not for the situation with msmbuilder where they now have both msmbuilder-3.3.0-np110py27_1 and msmbuilder-3.3.0-np110py27_2 (conda install msmbuilder installs _1 build, conda install msmbuilder=3.3.0-np110py27_2 doesn’t work).

All I worked out for now is downloading the tar.bz2 from https://conda.anaconda.org/omnia/osx-64 and conda install  msmbuilder-3.3.0-np110py27_2.tar.bz2

**Comment by rafwiewiora** [comment]
```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-3.18.6               |           py27_0         176 KB
    scikit-learn-0.17          |      np110py27_1         3.7 MB
    mdtraj-1.5.1               |      np110py27_0        16.6 MB
    msmbuilder-3.3.0           |      np110py27_1         1.0 MB
    ensembler-1.0.5            |           py27_0        23.9 MB
    ------------------------------------------------------------
                                           Total:        45.3 MB

The following NEW packages will be INSTALLED:

    ensembler:    1.0.5-py27_0     
    mdtraj:       1.5.1-np110py27_0
    msmbuilder:   3.3.0-np110py27_1
    scikit-learn: 0.17-np110py27_1 

The following packages will be UPDATED:

    conda:        3.18.5-py27_0 --> 3.18.6-py27_0    
```

**Comment by jchodera** [comment]
Can you post this in the `msmbuilder` issue tracker?  My understanding is that `conda` is supposed to install the *latest* build, not pick whichever build it likes!

**Comment by jchodera** [comment]
We may need to have them delete the earlier build from the [online `anaconda.org`](https://anaconda.org/omnia/msmbuilder/files) space.

**Comment by rafwiewiora** [comment]
Yeah, that's what I thought too! Ok posting now.

**Comment by rafwiewiora** [comment]
This is good to close.
