### ISSUE TITLE
conda installation forces OpenMM 6.3 and overrides 7.0beta

### ISSUE THREAD

**Issue by rafwiewiora** [choderalab/ensembler#68]
`conda install ensembler` forces installation of 6.3, and overrides my installation of 7.0-beta. Is this a problem at Ensembler conda set-up or something to do with conda not recognizing the beta as being OpenMM?

**Comment by jchodera** [comment]
The problem right now is that there is no way to tell `conda` that `openmm`, `openmm-dev`, and `openmm-beta` all conflict with each other.  You'll need to manually uninstall both with
```bash
conda remove --yes openmm openmm-dev openmm-beta
conda clean --yes -pltis
conda install --yes openmm
```
I would use `openmm` for `ensembler`, just to be consistent with how it was released.  Then switch back to `openmm-dev`.

We'll need some way to sort out all these versions at some point.

**Comment by jchodera** [comment]
We're looking into the use of [labels](https://www.continuum.io/blog/developer-blog/anaconda-cloud-introducing-labels) to do this.

**Comment by rafwiewiora** [comment]
Ah I see okay!
