### ISSUE TITLE
Update devtools to fix builds

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/ensembler#86]
The nightly builds are failing. I think this is related to changes made to `conda-build`, https://travis-ci.org/choderalab/ensembler#L916-L923 .

**Comment by jchodera** [comment]
I fixed that in this PR: https://github.com/choderalab/ensembler/pull/85

but the build is still failing because Ensembler seems to be full of broken code.

**Comment by jchodera** [comment]
I've only had a bit of time to slowly chisel away at all the broken things popping up in the tests in https://github.com/choderalab/ensembler/pull/85

**Comment by bas-rustenburg** [comment]
Ah, I didn't see any issues about it but turns out I missed the PR.  Just wanted to make sure it was on the radar.

**Comment by jchodera** [comment]
I get emails every night about the broken builds...
